#!/usr/bin/bash
#SBATCH -A MST109178                        # Account name/project number
#SBATCH -J M2fastq_preprocessing              # Job name
#SBATCH -p ngs53G                           # Partition Name 等同PBS裡面的 -q Queue name
#SBATCH -c 8                                # 使用的core數 請參考Queue資源設定
#SBATCH --mem=53g                           # 使用的記憶體量 請參考Queue資源設定
#SBATCH -o %j.log                           # Path to the standard output file I
#SBATCH -e %j.log                           # Path to the standard error ouput file
#SBATCH --mail-user=lohaochia@ntu.edu.tw    # email
#SBATCH --mail-type=END


module load biology
module load ABySS/2.3.8
 
###########
abyss-pe k=64 name=M4_assembly directory=/work/u1432917/M4extracted_reads_/ \
in='/work/u1432917/M4extracted_reads/R1_matched_reads.fq.gz /work/u1432917/M4extracted_reads/R2_matched_reads.fq.gz' \
B=4G
